apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # replace with your own email
    email: <your-email>
    
    # secret resource that will be used to store the account's private key
    privateKeySecretRef:
      name: letsencrypt-prod    
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
