imagePullSecrets:
  - name: my-regcred
ingress:
  enabled: true
  # run `kubectl get ingressclass` and use the value form there
  className: nginx 
  annotations: 
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     # use the value from `kubectl get clusterissuer`
     cert-manager.io/cluster-issuer: letsencrypt-prod 
  hosts:
    - host: brightc.k8s-course.co.za
      paths:
        - path: /
          pathType: Prefix
          service:
            name: nginx
            port: 80
        # add your prefix here for the backend
        - path: backendpath/
          pathType: Prefix
          service:
            name: backendservice # your backend service name
            port: 5003 # what port do you want to forward traffic on your backend?
  tls: 
   - secretName: nginx-tls-secret
     hosts:
